snowflake-dw:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: nq03221.us-central1.gcp

      # User/password auth
      user: DBT_USER
      password: DBT_PASSWORD

      role: DBT_ROLE
      database: AIRBYTE_DATABASE
      warehouse: AIRBYTE_WAREHOUSE
      schema: DW_SCHEMA
      threads: 1
      client_session_keep_alive: False
      query_tag: dbt-q

      # optional
      connect_retries: 0 # default 0
      connect_timeout: 10 # default: 10
      retry_on_database_errors: False # default: false 
      retry_all: False  # default: false